"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "./components/navigation/Navigation";
import { Footer } from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function searchHandler(search: string) {
  "use client";
  console.log(search);
}
function toggleMenu() {
  "use client";
  console.log("toggle menu");
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation
          search=""
          searchHandler={searchHandler}
          toggleMenu={toggleMenu}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
